# Generated by Django 5.1.6 on 2026-01-23 14:12

import news_site_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.FilePathField(path=news_site_app.models.item_description_path)),
                ('material', models.CharField(max_length=20)),
                ('clothing_type', models.CharField(max_length=20)),
                ('clothing_color', models.CharField(max_length=20)),
                ('clothing_size', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.FilePathField(path=news_site_app.models.images_path)),
                ('news_text', models.FilePathField(path=news_site_app.models.news_text_path)),
                ('author', models.CharField(max_length=70)),
            ],
        ),
    ]
