# Generated by Django 5.1.6 on 2026-01-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_text',
        ),
    ]
