# Generated by Django 5.1.6 on 2026-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site_app', '0002_remove_item_description_remove_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=34345, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.TextField(default=3434),
            preserve_default=False,
        ),
    ]
