# Generated by Django 5.1.6 on 2026-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site_app', '0003_news_image_news_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_subtitle',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
    ]
