# Generated by Django 5.1.6 on 2026-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site_app', '0004_item_description_item_photo_news_news_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('Нов', 'Новость'), ('Стат', 'Статья')], default=45, max_length=30),
            preserve_default=False,
        ),
    ]
